name: "linux-amd64"

runs:
  using: composite
  steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install nasm
        mkdir -p $GITHUB_WORKSPACE/local_amd64/lib

    - name: Install vcpkg
      shell: bash
      run: |
        git clone https://github.com/microsoft/vcpkg builder
        ./builder/bootstrap-vcpkg.sh
        cp vcpkg/linux-amd64-static.cmake builder/triplets/community

    - name: Build libheif
      shell: bash
      run: |
        ./builder/vcpkg install "libheif:linux-amd64-static"

    - name: Prepare dependencies
      shell: bash
      run: |
        cp -r $GITHUB_WORKSPACE/builder/installed/linux-amd64-static/include $GITHUB_WORKSPACE/local_amd64/include
        cp $GITHUB_WORKSPACE/builder/installed/linux-amd64-static/lib/*.a $GITHUB_WORKSPACE/local_amd64/lib/
        rm $GITHUB_WORKSPACE/local_amd64/lib/libpng.a

    - name: Zip local
      shell: bash
      run: |
        cd $GITHUB_WORKSPACE/local_amd64
        7z a -tzip -mx=9 $GITHUB_WORKSPACE/local_linux_amd64.zip include lib

    - name: Save artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-linux-amd64
        path: "*.zip"